### ISSUE TITLE
Vercel deployment.

### ISSUE THREAD

**Issue by ianhobbs** [BartoszJarocki/cv#21]
Sorry it's my first deployment in V.

Getting this error in Vercel.

```
Running "yarn dev"
yarn run v1.22.17
$ next dev
 ⚠ You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000
```

I presume it's the lack of .env ?

**Comment by aalu-love** [comment]
Issue #27 

It happens when the default **PORT** from Next.js is unavailable in the Vercel Environment. Checking any of the deployed sites that have **3000** PORT in use.

Also, making a .env will not help for now due to the system requirements that may cause it to fail in the production environment.

[https://github.com/vercel/next.js/issues/56948](https://github.com/vercel/next.js/issues/56948)

[https://github.com/vercel/next.js/discussions/58523](https://github.com/vercel/next.js/discussions/58523)

**Comment by feiyihx** [comment]
I'm not sure how did you link github and vercel. What I did is:
1. add a new project on vercel,
2. select next.js,
3. create a new github repo,
4. git clone the new repo to local and delete everything but .git folder,
5. copy your modified BartoszJarocki/cv to the new local repo fold and git push,
6. after about 3 minutes vercel will complete the deployment.


https://nextjs-cc-pi.vercel.app/
